openapi: 3.0.1
info:
  title: Common
  version: v1

paths:

components:
  schemas:
    TickerPrice:
      type: object
      properties:
        symbol:
          type: string
        broker:
          $ref: '#/components/schemas/BrokerEnum'
        price:
          type: string

    TickerBase:
      type: object
      properties:
        symbol:
          type: string
        broker:
          type: string
          enum:
            - BYBIT

    BrokerEnum:
      type: string
      enum:
        - BYBIT
        - BINANCE
        - OKEX
        - POLONIX
        - HUOBI
